# File: azure-pipelines.yml
trigger:
- main

resources:
  repositories:
    - repository: templates   # nombre de repositorio
      type: github
      name: nahuic72/templates
      endpoint: github.com_nahuic72  # service connection de github

extends:
  template: start.yml@templates  # esta palabra templates es el nombre del repository
  parameters:
    buildSteps:  
      - bash: echo Test # Esto si pasa como un buildStep en el start.yml
        displayName: succeed
      - bash: echo "Test"
        displayName: succeed
      # El paso siguiente es rechazado lanzando un error de sintaxis YAML: Unexpected value 'CmdLine@2'
      - task: CmdLine@2
        inputs:
          script: echo "Script Test"
      # El paso siguiente es rechazado lanzando un error de sintaxis YAML: Unexpected value 'CmdLine@2'
      - script: echo "Script Test"